from django.db import models

# Create your models here.
class Countries(models.Model):
    unCountryCode = models.IntegerField(primary_key=True)
    countryISO2 = models.CharField(max_length=3)
    countryISO3 = models.CharField(max_length=4)
    countryName = models.CharField(max_length=250)

    def __str__(self):
        return self.countryName

class CountryGPD(models.Model):
    countryCode = models.CharField(max_length=4, primary_key=True)
    subjectCode = models.CharField(max_length=15)
    countryName = models.CharField(max_length=255)
    gdp2002 = models.FloatField()
    gdp2003 = models.FloatField()
    gdp2004 = models.FloatField()
    gdp2005 = models.FloatField()
    gdp2006 = models.FloatField()
    gdp2007 = models.FloatField()
    gdp2008 = models.FloatField()
    gdp2009 = models.FloatField()
    gdp2010 = models.FloatField()
    gdp2011 = models.FloatField()
    gdp2012 = models.FloatField()
    gdp2013 = models.FloatField()
    gdp2014 = models.FloatField()
    gdp2015 = models.FloatField()
    gdp2016 = models.FloatField()
    gdp2017 = models.FloatField()
    gdp2018 = models.FloatField()

class CountryUE(models.Model):
    countryCodeUE = models.CharField(max_length=4, primary_key=True)
    subjectCodeUE = models.CharField(max_length=4)
    countryNameUE = models.CharField(max_length=255)
    ue2002 = models.FloatField()
    ue2003 = models.FloatField()
    ue2004 = models.FloatField()
    ue2005 = models.FloatField()
    ue2006 = models.FloatField()
    ue2007 = models.FloatField()
    ue2008 = models.FloatField()
    ue2009 = models.FloatField()
    ue2010 = models.FloatField()
    ue2011 = models.FloatField()
    ue2012 = models.FloatField()
    ue2013 = models.FloatField()
    ue2014 = models.FloatField()
    ue2015 = models.FloatField()
    ue2016 = models.FloatField()
    ue2017 = models.FloatField()
    ue2018 = models.FloatField()

class CountryPopn(models.Model):
    countryCodePopn = models.CharField(max_length=4, primary_key=True)
    weoPopnCode = models.CharField(max_length=5)
    countryNamePopn = models.CharField(max_length=250)
    popn2002 = models.FloatField()
    popn2003 = models.FloatField()
    popn2004 = models.FloatField()
    popn2005 = models.FloatField()
    popn2006 = models.FloatField()
    popn2007 = models.FloatField()
    popn2008 = models.FloatField()
    popn2009 = models.FloatField()
    popn2010 = models.FloatField()
    popn2011 = models.FloatField()
    popn2012 = models.FloatField()
    popn2013 = models.FloatField()
    popn2014 = models.FloatField()
    popn2015 = models.FloatField()
    popn2016 = models.FloatField()
    popn2017 = models.FloatField()
    popn2018 = models.FloatField()

class CountryPoverty(models.Model):
    countryCodePov = models.CharField(max_length=4, primary_key=True)
    indicatorCode = models.CharField(max_length=25)
    countryNamePov = models.CharField(max_length=250)
    pov2002 = models.FloatField()
    pov2003 = models.FloatField()
    pov2004 = models.FloatField()
    pov2005 = models.FloatField()
    pov2006 = models.FloatField()
    pov2007 = models.FloatField()
    pov2008 = models.FloatField()
    pov2009 = models.FloatField()
    pov2010 = models.FloatField()
    pov2011 = models.FloatField()
    pov2012 = models.FloatField()
    pov2013 = models.FloatField()
    pov2014 = models.FloatField()
    pov2015 = models.FloatField()
    pov2016 = models.FloatField()
    pov2017 = models.FloatField()
    pov2018 = models.FloatField()